### PR TITLE
Update UI

### LINKED ISSUE #68: Code formatting
- Improving CSS
- Adding a loading component
- Improving responsiveness
- Folders restructuring

### PR DESCRIPTION
**Pull request by itsksquare**
This PR includes
- Updated UI,
-  Added features like `View form`, `Bulk Signups`, `List of village names`, `ability to add a new village`.

fixes #68

### CODE REVIEW

**Comment by mayureshagashe2105** [comment]
@itsksquare has sent me a pre-view link for his PR. @Scholasticpal please go through the link to validate and review the PR.
[https://heritians.vercel.app/](https://heritians.vercel.app/)

**Review by Scholasticpal — CHANGES_REQUESTED** [review]
please go through the bullet points I added on https://github.com/Heritians/Connecting-Villages/pull/69/

**Comment by Scholasticpal** [comment]
@mayuresh I have reviewed the website and have discussed the left parts with @itsksquare . 
please merge this commit to another branch as of now as responsiveness is being worked upon. That will then be covered in a different issue.

**Review by Scholasticpal — APPROVED** [review]

**Comment by Scholasticpal** [comment]
@mayureshagashe2105 has conveyed to me that we'll be using laptops af of now, so I have pushed your updates @itsksquare .
Thank you for your wonderful contribution!

**Pull request merged**
