### PR TITLE
Bug Fixes, Better protected routes, Removed unwanted lines

### PR DESCRIPTION
**Pull request by itsksquare**
This PR includes the following changes:
- Added descriptions to the About Us page and Village Cards on home page
- Better Protected routes
- Removed unwanted lines and comments
- Other minor fixes and improvements

### CODE REVIEW

**Comment by Scholasticpal** [comment]
The changes look good to me, however, this is a direct commit to Heritians main branch. 
@mayureshagashe2105 @HemanthSai7 are we able to merge directly to the main now?

**Comment by HemanthSai7** [comment]
@Scholasticpal Is there any issue in merging to the main?

**Comment by Scholasticpal** [comment]
no, the frontend team is fine with it @HemanthSai7, but since previously we weren't making commits directly to the main so had to know backend teams take on it

**Review by Scholasticpal — APPROVED** [review]

**Comment by Scholasticpal** [comment]
i am merging the code now. Thank you for your contribution @itsksquare

**Pull request merged**
